# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bf7f3a1c944cff194c1bed80ace239b0556f40ac7f47c991133163f9288c17a56f998443db38072a9cc0a5ea86070efb441168b72398b1a46c4c4e7bdabf0c4

test:
  secret_key_base: ab2655a03d6c08cac77aded4f34202b584f17b846d910e1a8586d46834a953b656d570e275ca055d7ba8705e273c5dc013cf93fa1599d0c6f8e66ef2a1f7476a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
